services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - logs:/app/logs
    networks:
      - app-network
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]  # Fixed endpoint
      interval: 30s
      timeout: 10s
      retries: 3
    expose:
      - "8000"  # Required for nginx communication

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      app:
        condition: service_healthy

volumes:
  data:
  logs:

networks:
  app-network:
    driver: bridge
    internal: true