name: Deployment Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euxo pipefail
            cd /var/www/fastapi-book-project
            
            # 1. Pull latest code
            git fetch --all
            git reset --hard origin/main
            
            # 2. Copy production env file
            cp .env.production .env
            
            # 3. Build and deploy
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml build --no-cache
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            
            # 4. Cleanup
            docker image prune -af --filter "until=24h"
            docker builder prune -af
            
            # 5. Verify deployment
            curl --retry 3 --retry-delay 5 --max-time 10 --fail http://localhost/api/v1/books/1