name: Deployment Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: production  # Only enable after creating in repo settings
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euxo pipefail
            cd /var/www/fastapi-book-project
            
            # Atomic deployment
            git fetch --all
            git reset --hard origin/main
            
            # Build with cache cleanup
            docker compose -f docker-compose.prod.yml build --no-cache
            
            # Zero-downtime update
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            
            # System cleanup
            docker system prune -af --filter "until=24h"
            
            # Health verification
            curl --retry 3 --retry-delay 5 --fail http://localhost/healthcheck