name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Deploy Application
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh ubuntu@$SERVER_IP << 'EOF'
          cd /var/www/fastapi-book-project
          git reset --hard HEAD
          git pull origin main
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
          docker system prune -f
          EOF